# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Git clone whisper.
  git:
    dest: "{{ whisper_git_dest }}"
    repo: "{{ whisper_git_uri }}"
    update: "{{ whisper_git_update|default(omit) }}"
    version: "{{ whisper_git_version }}"

- name: Set whisper_pip_name to local git repo.
  set_fact:
    whisper_pip_name: "file://{{ whisper_git_dest }}"

- include: pip.yaml
